#!/usr/bin/env bash

# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

set -e

source "$(readlink -f $(dirname ${0}))/setupenv.src"

VERSION=$(cat VERSION)

###############################################################################

# If no LOCAL_BUILD environment variable is set, we configure the `go build` command
# to build for the local/default OS and ARCH and without CGO enablement.
if [[ -z "$LOCAL_BUILD" ]]; then
  CGO_ENABLED=0 GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) go build \
    -a \
    -o ${BINARY_PATH}/rel/machine-controller \
    -ldflags "-X main.version=$VERSION-$(git rev-parse HEAD)" \
    cmd/machine-controller/main.go

# If the LOCAL_BUILD environment variable is set, we simply run `go build`.
else
  go build \
    -o ${BINARY_PATH}/machine-controller \
    -ldflags "-X main.version=$VERSION-$(git rev-parse HEAD)" \
    cmd/machine-controller/main.go
fi
