#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

source "$(dirname ${0})/setupenv.src"

VERSION=$(cat VERSION)

###############################################################################

# If no LOCAL_BUILD environment variable is set, we configure the `go build` command
# to build for linux OS, amd64 architectures and without CGO enablement.
if [[ -z "$LOCAL_BUILD" ]]; then
  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -mod=vendor \
    -a \
    -o ${BINARY_PATH}/rel/machine-controller \
    -ldflags "-X main.version=$VERSION-$(git rev-parse HEAD)" \
    cmd/machine-controller/main.go

# If the LOCAL_BUILD environment variable is set, we simply run `go build`.
else
  go build \
    -mod=vendor \
    -o ${BINARY_PATH}/machine-controller \
    -ldflags "-X main.version=$VERSION-$(git rev-parse HEAD)" \
    cmd/machine-controller/main.go
fi
