#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

source "$(dirname ${0})/setupenv.src"

go install golang.org/x/lint/golint

###############################################################################
PACKAGES="$(go list -e ./... | grep -vE '/internal/flags')"
PACKAGES_DIRS="$(echo ${PACKAGES} | sed "s|github.com/gardener/machine-controller-manager-provider-alicloud|.|g")"

# Execute static code checks.
echo "Running go vet..."
go vet ${PACKAGES}

# Execute automatic code formatting directive.
echo "Running gofmt..."
gofmt -l -w -s ${PACKAGES_DIRS}

# Execute lint checks.
echo "Running golint..."
for package in ${PACKAGES_DIRS}; do
    golint -set_exit_status $(find $package -maxdepth 1 -name "*.go" | grep -vE 'zz_generated|_test.go')
done
echo "Check script has passed successfully"
